export * from "./user.constants";
export * from "./alert.constants";
export * from "./cards.constants";
export const baseURL = "https://uxcandy.com/~shapoval/test-task-backend";
export const token = "beejee";
export const statusReady = 10;
export const statusNotReady = 0;
export const sortConstants = ["username", "email", "status"];
export const MAX_UPLOAD_WIDTH = 320;
export const MAX_UPLOAD_HEIGHT = 240;
